#!/usr/bin/env bash
# Generate a .env with strong random secrets for a NovaCortex self-host deployment.
# Usage: ./scripts/gen-env.sh [--unraid] [--local-embeddings|--local-ai] [path]
#                                                            (default path: .env)
#   --unraid            APPDATA=/mnt/user/appdata/novacortex instead of ./data.
#                       Auto-detected when this runs on the Unraid server itself;
#                       pass it explicitly when generating the .env elsewhere.
#   --local-embeddings  fully-local semantic search via the Ollama sidecar
#                       (compose profile "local-ai")
#   --local-ai          --local-embeddings PLUS the local intelligence layer
#                       (LLM fact extraction + update resolution, qwen3:8b)
set -euo pipefail

MODE="default"
ENV_FILE=".env"
# Unraid's Docker Compose Manager keeps projects on the FAT32 boot flash, which
# has no Unix ownership — SurrealDB, Qdrant and Redis all fail there. So on
# Unraid the data root has to be an absolute path on the array/pool.
UNRAID=false
[ -f /etc/unraid-version ] && UNRAID=true
for arg in "$@"; do
  case "$arg" in
    --unraid) UNRAID=true ;;
    --local-embeddings) MODE="embeddings" ;;
    --local-ai) MODE="ai" ;;
    *) ENV_FILE="$arg" ;;
  esac
done

if [ "$UNRAID" = true ]; then
  APPDATA_VALUE="/mnt/user/appdata/novacortex"
  APPDATA_NOTE="# Unraid appdata: survives docker.img rebuilds, covered by appdata backups.
# Do NOT make this relative — Compose Manager projects live on the FAT32 boot
# flash, which cannot hold Redis/SurrealDB/Qdrant data."
else
  APPDATA_VALUE="./data"
  APPDATA_NOTE="# Generic Docker host: keep data next to the compose file.
# On Unraid use /mnt/user/appdata/novacortex instead (or re-run with --unraid)."
fi

if [ -e "$ENV_FILE" ]; then
  echo "Refusing to overwrite existing $ENV_FILE. Remove it first if you really mean to." >&2
  exit 1
fi

if ! command -v openssl >/dev/null 2>&1; then
  echo "openssl is required to generate secrets." >&2
  exit 1
fi

rand() { openssl rand -base64 48 | tr -dc 'A-Za-z0-9' | cut -c1-40; }

case "$MODE" in
  embeddings)
    AI_BLOCK=$(cat <<'EOB'
# --- Semantic search: fully-local via the Ollama sidecar ---
# Start the stack with: docker compose --profile local-ai up -d
# No memory text ever leaves this host. NOTE: nomic-embed-text produces 768-dim
# vectors — QDRANT_VECTOR_SIZE must match and needs a FRESH Qdrant collection.
OPENAI_BASE_URL=http://ollama:11434/v1
OPENAI_API_KEY=ollama
EMBEDDING_MODEL=nomic-embed-text
QDRANT_VECTOR_SIZE=768
OLLAMA_PULL=nomic-embed-text
# Add the local intelligence layer later by setting (and re-pulling):
# LLM_MODEL=qwen3:8b
# OLLAMA_PULL=nomic-embed-text qwen3:8b
EOB
)
    ;;
  ai)
    AI_BLOCK=$(cat <<'EOB'
# --- Fully-local AI: semantic search + memory intelligence (Ollama sidecar) ---
# Start the stack with: docker compose --profile local-ai up -d
# No memory text ever leaves this host. NOTE: nomic-embed-text produces 768-dim
# vectors — QDRANT_VECTOR_SIZE must match and needs a FRESH Qdrant collection.
# qwen3:8b needs ~5-6 GB RAM/VRAM; pick a smaller model on constrained hardware.
OPENAI_BASE_URL=http://ollama:11434/v1
OPENAI_API_KEY=ollama
EMBEDDING_MODEL=nomic-embed-text
QDRANT_VECTOR_SIZE=768
# Intelligence layer: LLM fact extraction + update resolution (append-only).
LLM_MODEL=qwen3:8b
OLLAMA_PULL=nomic-embed-text qwen3:8b
EOB
)
    ;;
  *)
    AI_BLOCK=$(cat <<'EOB'
# --- Optional: semantic search + memory intelligence ---
# Setting OPENAI_API_KEY sends memory text to OpenAI for embeddings; adding
# LLM_MODEL additionally enables LLM fact extraction + update resolution.
# For FULLY-LOCAL operation instead, re-run this script with
# --local-embeddings (search only) or --local-ai (search + intelligence).
# OPENAI_API_KEY=sk-...
# OPENAI_BASE_URL=
# EMBEDDING_MODEL=text-embedding-3-small
# QDRANT_VECTOR_SIZE=1536
# LLM_MODEL=gpt-4o-mini
EOB
)
    ;;
esac

cat > "$ENV_FILE" <<EOF
# Generated by scripts/gen-env.sh — strong random secrets. KEEP PRIVATE, never commit.

# --- Required secrets ---
SURREALDB_USER=root
SURREALDB_PASS=$(rand)
REDIS_PASSWORD=$(rand)
NEXTAUTH_SECRET=$(rand)
JWT_SECRET=$(rand)

# --- Data root ---
${APPDATA_NOTE}
APPDATA=${APPDATA_VALUE}

# --- Host ports ---
# Check these are free BEFORE starting the stack. Port 3000 is a popular default
# (Grafana, Homepage, Overseerr, …), so on a busy server set e.g. WEB_PORT=3100.
WEB_PORT=3000
API_PORT=3001

# Pinned image version (the known-good release tag on GHCR)
NOVACORTEX_VERSION=1.3.2

# Namespace / database (defaults are fine for a single deployment)
SURREALDB_NAMESPACE=novacortex
SURREALDB_DATABASE=production

${AI_BLOCK}

# --- Optional: hardening / licensing ---
# Lock the API CORS to your UI origin(s) (comma-separated). Unset = permissive.
# CORS_ORIGINS=http://localhost:3000
# Pro/Enterprise license key. Empty = free tier.
# LICENSE_KEY=
# Requests/min across data-plane routes (default: license tier; 0/off disables).
# API_RATE_LIMIT=
EOF

chmod 600 "$ENV_FILE"
echo "Wrote $ENV_FILE (chmod 600) with strong random secrets."
echo "Data root: APPDATA=${APPDATA_VALUE}$([ "$UNRAID" = true ] && echo '  (Unraid)')"
echo "Ports: WEB_PORT=3000, API_PORT=3001 — change them if either is already in use."
case "$MODE" in
  embeddings)
    echo "Local embeddings preconfigured. Start the stack with:"
    echo "  docker compose --profile local-ai up -d"
    ;;
  ai)
    echo "Local embeddings + intelligence layer preconfigured. Start the stack with:"
    echo "  docker compose --profile local-ai up -d"
    echo "(first start pulls nomic-embed-text + qwen3:8b — a few GB, one-time)"
    ;;
  *)
    echo "Next: set OPENAI_API_KEY for semantic search (or re-run with --local-embeddings / --local-ai), then:"
    echo "  docker compose up -d"
    ;;
esac
