#!/usr/bin/env bash
# Generate a .env with strong random secrets for a NovaCortex self-host deployment.
# Usage: ./scripts/gen-env.sh [--local-embeddings] [path]   (default path: .env)
#   --local-embeddings  preconfigure fully-local semantic search via the Ollama
#                       sidecar (compose profile "local-embeddings")
set -euo pipefail

LOCAL_EMBEDDINGS=false
ENV_FILE=".env"
for arg in "$@"; do
  case "$arg" in
    --local-embeddings) LOCAL_EMBEDDINGS=true ;;
    *) ENV_FILE="$arg" ;;
  esac
done

if [ -e "$ENV_FILE" ]; then
  echo "Refusing to overwrite existing $ENV_FILE. Remove it first if you really mean to." >&2
  exit 1
fi

if ! command -v openssl >/dev/null 2>&1; then
  echo "openssl is required to generate secrets." >&2
  exit 1
fi

rand() { openssl rand -base64 48 | tr -dc 'A-Za-z0-9' | cut -c1-40; }

if [ "$LOCAL_EMBEDDINGS" = true ]; then
  EMBEDDING_BLOCK=$(cat <<'EOB'
# --- Semantic search: fully-local via the Ollama sidecar ---
# Start the stack with: docker compose --profile local-embeddings up -d
# No memory text ever leaves this host. NOTE: nomic-embed-text produces 768-dim
# vectors — QDRANT_VECTOR_SIZE must match and needs a FRESH Qdrant collection.
OPENAI_BASE_URL=http://ollama:11434/v1
OPENAI_API_KEY=ollama
EMBEDDING_MODEL=nomic-embed-text
QDRANT_VECTOR_SIZE=768
EOB
)
else
  EMBEDDING_BLOCK=$(cat <<'EOB'
# --- Optional: semantic search ---
# Setting OPENAI_API_KEY sends memory text to OpenAI for embeddings.
# For FULLY-LOCAL embeddings instead, re-run this script with
# --local-embeddings (uses the bundled Ollama sidecar), or point
# OPENAI_BASE_URL at any OpenAI-compatible server yourself.
# OPENAI_API_KEY=sk-...
# OPENAI_BASE_URL=
# EMBEDDING_MODEL=text-embedding-3-small
# QDRANT_VECTOR_SIZE=1536
EOB
)
fi

cat > "$ENV_FILE" <<EOF
# Generated by scripts/gen-env.sh — strong random secrets. KEEP PRIVATE, never commit.

# --- Required secrets ---
SURREALDB_USER=root
SURREALDB_PASS=$(rand)
REDIS_PASSWORD=$(rand)
NEXTAUTH_SECRET=$(rand)
JWT_SECRET=$(rand)

# --- Data + ports ---
# Unraid: /mnt/user/appdata/novacortex   |   generic Docker host: ./data
APPDATA=./data
API_PORT=3001
WEB_PORT=3000

# Pinned image version (the known-good release tag on GHCR)
NOVACORTEX_VERSION=1.2.1

# Namespace / database (defaults are fine for a single deployment)
SURREALDB_NAMESPACE=novacortex
SURREALDB_DATABASE=production

${EMBEDDING_BLOCK}

# --- Optional: hardening / licensing ---
# Lock the API CORS to your UI origin(s) (comma-separated). Unset = permissive.
# CORS_ORIGINS=http://localhost:3000
# Pro/Enterprise license key. Empty = free tier.
# LICENSE_KEY=
# Requests/min across data-plane routes (default: license tier; 0/off disables).
# API_RATE_LIMIT=
EOF

chmod 600 "$ENV_FILE"
echo "Wrote $ENV_FILE (chmod 600) with strong random secrets."
if [ "$LOCAL_EMBEDDINGS" = true ]; then
  echo "Local embeddings preconfigured. Start the stack with:"
  echo "  docker compose --profile local-embeddings up -d"
else
  echo "Next: set OPENAI_API_KEY for semantic search (or re-run with --local-embeddings), then:"
  echo "  docker compose up -d"
fi
